export const INITIAL_CALL_LOGS = [
  {
    id: '1',
    name: 'Balram Suman',
    avatarUri: 'https://i.pravatar.cc/150?img=11',
    callType: 'outgoing',
    date: '24 June, 8:14 pm',
    callIconType: 'voice',
  },
  {
    id: '2',
    name: 'Epic Games',
    avatarUri: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?w=300',
    callType: 'incoming',
    date: '8 August, 8:14 pm',
    callIconType: 'video',
  },
  {
    id: '3',
    name: 'Geeta Bisht',
    avatarUri: 'https://i.pravatar.cc/150?img=47',
    callType: 'missed',
    date: '24 June, 8:14 pm',
    callIconType: 'voice',
    isMissed: true,
  },
  {
    id: '4',
    name: 'Uttam Rajpurohit',
    avatarUri: 'https://i.pravatar.cc/150?img=33',
    callType: 'outgoing',
    date: '24 June, 8:14 pm',
    callIconType: 'voice',
  },
  {
    id: '5',
    name: 'Omrishi Sharma',
    avatarUri: 'https://i.pravatar.cc/150?img=60',
    callType: 'missed-x',
    date: '24 June, 8:14 pm',
    callIconType: 'video',
  },
  {
    id: '6',
    name: 'Sana Khan',
    avatarUri: 'https://i.pravatar.cc/150?img=43',
    callType: 'outgoing',
    date: '24 June, 8:14 pm',
    callIconType: 'video',
  },
  {
    id: '7',
    name: 'Balram Suman',
    avatarUri: 'https://i.pravatar.cc/150?img=68',
    callType: 'missed',
    date: '24 June, 8:14 pm',
    callIconType: 'voice',
    isMissed: true,
  },
  {
    id: '8',
    name: 'Govind Jain',
    initials: 'GJ',
    initialsColor: '#9C88FF',
    callType: 'incoming',
    date: '24 June, 8:14 pm',
    callIconType: 'voice',
  },
  {
    id: '9',
    name: 'Omrishi Sharma',
    avatarUri: 'https://i.pravatar.cc/150?img=12',
    callType: 'outgoing',
    date: '24 June, 8:14 pm',
    callIconType: 'voice',
  },
];

export const MOCK_CALL_HISTORY_DETAILS = {
  id: '1',
  name: 'Balram Suman',
  status: 'Online',
  avatarUri: 'https://i.pravatar.cc/150?img=11',
  lastCallSummary: {
    type: 'Outgoing',
    callType: 'outgoing',
    date: '24 June, 8:14 pm',
    duration: '1:32m',
  },
  history: [
    {
      id: 'h1',
      type: 'Outgoing call',
      callType: 'outgoing',
      date: '24 June, 8:14 pm',
      duration: '32s',
    },
    {
      id: 'h2',
      type: 'Incoming call',
      callType: 'incoming',
      date: '24 June, 8:14 pm',
      duration: '1:32m',
    },
    {
      id: 'h3',
      type: 'Missed call',
      callType: 'missed',
      date: '24 June, 8:14 pm',
      duration: '---',
    },
  ],
};
