export const EMOJI_CATEGORIES = [
  { title: 'Recently Used', key: 'recent', icon: 'time-outline' },
  { title: 'Smileys & Emotion', key: 'smileys', icon: 'happy-outline' },
  { title: 'People & Body', key: 'people', icon: 'body-outline' },
  { title: 'Animals & Nature', key: 'animals', icon: 'leaf-outline' },
  { title: 'Food & Drink', key: 'food', icon: 'pizza-outline' },
  { title: 'Activities', key: 'activities', icon: 'football-outline' },
  { title: 'Travel & Places', key: 'travel', icon: 'airplane-outline' },
  { title: 'Objects', key: 'objects', icon: 'bulb-outline' },
  { title: 'Symbols', key: 'symbols', icon: 'heart-outline' },
  { title: 'Flags', key: 'flags', icon: 'flag-outline' },
];

export const EMOJI_DATA = {
  smileys: [
    "😀", "😃", "😄", "😁", "😆", "😅", "😂", "🤣", "😊", "😇", "🙂", "🙃", "😉", "😌", "😍", "🥰", "😘", "😗", "😙", "😚", "😋", "😛", "😝", "😜", "🤪", "🤨", "🧐", "🤓", "😎", "🤩", "🥳", "😏", "😒", "😞", "😔", "😟", "😕", "🙁", "☹️", "😣", "😖", "😫", "😩", "🥺", "😢", "😭", "😤", "😠", "😡", "🤬", "🤯", "😳", "🥵", "🥶", "😱", "😨", "😰", "😥", "😓", "🤗", "🤔", "🤭", "🤫", "🤥", "😶", "😐", "😑", "😬", "🙄", "😯", "😦", "😧", "😮", "😲", "🥱", "😴", "🤤", "😪", "😵", "🤐", "🥴", "🤢", "🤮", "🤧", "😷", "🤒", "🤕", "🤑", "🤠", "😈", "👿", "👹", "👺", "🤡", "💩", "👻", "💀", "☠️", "👽", "👾", "🤖", "🎃", "😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾"
  ],
  people: [
    "👋", "🤚", "🖐", "✋", "🖖", "👌", "✌️", "🤞", "🤟", "🤘", "🤙", "👈", "👉", "👆", "🖕", "👇", "☝️", "👍", "👎", "✊", "👊", "🤛", "🤜", "👏", "🙌", "👐", "🤲", "🤝", "🙏", "✍️", "💅", "🤳", "💪", "🦾", "🦿", "🦵", "🦶", "👂", "🦻", "👃", "🧠", "🦷", "🦴", "👀", "👁", "👅", "👄", "💋", "🩸", "👶", "👧", "🧒", "👦", "👩", "🧑", "👨", "👴", "👵", "👨‍⚕️", "👩‍⚕️", "👨‍🎓", "👩‍🎓", "👨‍🏫", "👩‍🏫", "👨‍⚖️", "👩‍⚖️", "👨‍🌾", "👩‍🌾", "👨‍🍳", "👩‍🍳", "👨‍🔧", "👩‍🔧", "👨‍🏭", "👩‍🏭", "👨‍💼", "👩‍💼", "👨‍🔬", "👩‍🔬", "👨‍💻", "👩‍💻", "👨‍🎤", "👩‍🎤", "👨‍🎨", "👩‍🎨", "👨‍✈️", "👩‍✈️", "👨‍🚀", "👩‍🚀", "👨‍🚒", "👩‍🚒", "👮‍♂️", "👮‍♀️", "🕵️‍♂️", "🕵️‍♀️", "💂‍♂️", "💂‍♀️", "👷‍♂️", "👷‍♀️", "👸", "🤴", "👰", "🤵", "🤰", "🤱"
  ],
  animals: [
    "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐽", "🐸", "🐵", "🙈", "🙉", "🙊", "🐒", "🐔", "🐧", "🐦", "🐤", "🐣", "🐥", "🦆", "🦅", "🦉", "🦇", "🐺", "🐗", "🐴", "🦄", "🐝", "🐛", "🦋", "🐌", "🐞", "🐜", "🦟", "🦗", "🕷", "🕸", "🦂", "🐢", "🐍", "🦎", "🐙", "🦑", "🦞", "🦀", "🐡", "🐠", "🐟", "🐬", "🐳", "🐋", "🦈", "🐊", "🐅", " leopards", "🐆", "🦓", "🦍", "🦧", "🐘", "🦛", "🦏", "🐪", "🐫", "🦒", "🦘", "🐃", "🐂", "🐄", "🐎", "🐖", "🐏", "🐑", "🐐", "🦌", "🐕", "🐈", "🐓", "🦃", "🦚", "🦜", "🦢", "🦩", "🕊", "🐇", "🦝", "🦡", "🦦", "🦥", "🐁", "🐀", "🐿", "🦔", "🐾", "🐉", "🐲", "🌵", "🎄", "🌲", "🌳", "🌴", "🌱", "🌿", "☘️", "🍀", "🍁", "🍂", "🍃"
  ],
  food: [
    "🍏", "🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🍈", "🍒", "🍑", "🥭", "🍍", "🥥", "🥝", "🍅", "🍆", "🥑", "🥦", "🥬", "🥒", "🌶", "🌽", "🥕", "🥔", "🍠", "🥐", "🥯", "🍞", "🥖", "🥨", "🧀", "🥚", "🍳", "🥞", "🧇", "🥓", "🥩", "🍗", "🍖", "🌭", "🍔", "🍟", "🍕", "🥪", "🌮", "🌯", "🥗", "🍿", "🧈", "🧂", "🥫", "🍱", "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍢", "🍣", "🍤", "🍥", "🍡", "🥟", "🥠", "🥡", "🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🥧", "🍫", "🍬", "🍭", "🍮", "🍯", "🍼", "🥛", "☕️", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥂", "🥃", "🥤", "🧉", "🥢", "🍽", "🍴", "🥄"
  ],
  activities: [
    "👾", "🎮", "🕹", "🎰", "🎳", "🎯", "🏈", "🏀", "⚽️", "⚾️", "🥎", "🎾", "🏐", "🏉", "🎱", "🥏", "🏓", "🏸", "🥅", "🏒", "🏑", "🥍", "🏏", "⛳️", "🏹", "🎣", "🤿", "🥊", "🥋", "⛸", "🎿", "🏂", "🛷", "🥌", "🏆", "🥇", "🥈", "🥉", "🏅", "🎖", "🎗", "🎫", "🎟", "🎪", "🎭", "🎨", "🎬", "🎤", "🎧", "🎼", "🎹", "🥁", "🎷", "🎺", "🎸", "🎻"
  ],
  travel: [
    "🚗", "🚕", "🚙", "🚌", "🚎", "🏎", "🚓", "🚑", "🚒", "🚐", "🚚", "🚛", "🚜", "🏍", "🛵", "🚲", "🛴", "🛹", "🚏", "⛽️", "🚨", "🚥", "🚦", "🚧", "⚓️", "⛵️", "🚤", "🛳", "🛥", "🚢", "✈️", "🛩", "🛫", "🛬", "🪂", "🦼", "🦽", "🛰", "🚀", "🛸", "🛎", "🧳", "🗻", "🌋", "🏔", "🏕", "🏖", "🏜", "🏝", "🏞", "🏟", "🏛", "🏢", "🏬", "🏣", "🏤", "🏥", "🏦", "🏨", "🏪", "🏫", "🏩", "💒", "🏰", "🏯"
  ],
  objects: [
    "⌚️", "📱", "📲", "💻", "⌨️", "🖥", "🖨", "鼠标", "🖲", "🎮", "🗜", "💽", "💾", "💿", "📀", "📼", "📷", "📸", "📹", "🎥", "📽", "🎞", "📞", "☎️", "📟", "📠", "📺", "📻", "🎙", "🎚", "🎛", "🧭", "📡", "🔋", "🔌", "💡", "🔦", "🕯", "🪔", "🗑", "🛢", "💸", "💵", "💴", "💶", "💷", "🪙", "💰", "💳", "💎", "⚖️", "🧰", "🔧", "🔨", "⚒", "🛠", "⛏", "🔩", "⚙️", "🧱", "⛓", "🧲", "🔫", "💣", "🧨", "🪓", "🔪", "🗡", "⚔️", "🛡", "🚬", "⚰️", "🪦", "⚱️", "🏺", "🔮", "📿", "🧿", "🧪", "🔬", "🔭", "📡", "🕳", "🩹", "🩺", "💊", "💉", "🧬"
  ],
  symbols: [
    "💘", "💝", "💖", "💗", "💓", "💞", "💕", "💟", "❣️", "💔", "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💤", "💢", "💬", "🗯", "💭", "💮", "♨️", "🛑", "🌀", "♠️", "♥️", "♦️", "♣️", "🃏", "🀄️", "🎴", "🔇", "🔈", "🔉", "🔊", "📢", "📣", "📯", "🔔", "🔕", "🎼", "🎵", "🎶", "💹", "🛃", "🛄", "🛅", "🚹", "🚺", "🚼", "🚻", "🚮", "🎦", "📶", "📳", "📴", "🔞", "☢️", "☣️", "⬆️", "↗️", "➡️", "↘️", "⬇️", "↙️", "⬅️", "↖️", "↕️", "↔️", "↩️", "↪️", "🛐", "⚛️", "🕉", "✡️", "☸️", "☯️", "✝️", "☪️", "☮️", "🕎"
  ],
  flags: [
    "🏁", "🚩", "🎌", "🏴", "🏳️", "🏳️‍🌈", "🏳️‍⚧️", "🏴‍☠️", "🇦🇫", "🇦🇱", "🇩🇿", "🇦🇩", "🇦🇴", "🇦🇬", "🇦🇷", "🇦🇲", "🇦🇺", "🇦🇹", "🇦🇿", "🇧🇸", "🇧🇭", "🇧🇩", "🇧🇧", "🇧🇪", "🇧🇿", "🇧🇯", "🇧🇹", "🇧🇴", "🇧🇦", "🇧🇷", "🇧🇬", "🇧🇫", "🇰🇭", "🇨🇲", "🇨🇦", "🇨🇱", "🇨🇳", "🇨🇴", "🇨🇬", "🇨🇩", "🇨🇷", "🇨🇮", "🇭🇷", "🇨🇺", "🇨🇼", "🇨🇾", "🇨🇿", "🇩🇰", "🇩🇯", "🇩🇲", "🇩🇴", "🇪🇨", "🇪🇬", "🇸🇻", "🇪🇪", "🇪🇹", "🇪🇺", "🇫🇯", "🇫🇮", "🇫🇷", "🇬🇦", "🇬🇪", "🇩🇪", "🇬🇭", "🇬🇷", "🇬🇹", "🇬🇳", "🇭🇹", "🇭🇳", "🇭🇰", "🇭🇺", "🇮🇸", "🇮🇳", "🇮🇩", "🇮🇷", "🇮🇶", "🇮🇪", "🇮🇱", "🇮🇹", "🇯🇲", "🇯🇵", "🇯🇴", "🇰🇿", "🇰🇪", "🇰🇼", "🇱🇦", "🇱🇻", "🇱🇧", "🇱🇷", "🇱🇾", "🇱🇹", "🇱🇺", "🇲🇬", "🇲🇾", "🇲🇱", "🇲🇹", "🇲🇽", "🇲🇨", "🇲🇳", "🇲🇪", "🇲🇦", "🇲🇿", "🇲🇲", "🇳🇵", "🇳🇱", "🇳🇿", "🇳🇮", "🇳🇪", "🇳🇬", "🇰🇵", "🇳🇴", "🇴🇲", "🇵🇰", "🇵🇸", "🇵🇦", "🇵🇾", "🇵🇪", "🇵🇭", "🇵🇱", "🇵🇹", "🇵🇷", "🇶🇦", "🇷🇴", "🇷🇺", "🇷🇼", "🇸🇦", "🇸🇳", "🇷🇸", "🇸🇬", "🇸🇰", "🇸🇮", "🇿🇦", "🇰🇷", "🇪🇸", "🇱🇰", "🇸🇩", "🇸🇪", "🇨🇭", "🇸🇾", "🇹🇼", "🇹🇭", "🇹🇷", "🇺🇬", "🇺🇦", "🇦🇪", "🇬🇧", "🇺🇸", "🇺🇾", "🇺🇿", "🇻🇦", "🇻🇪", "🇻🇳", "🇾🇪", "🇿🇲", "🇿🇼"
  ]
};

export const EMOJI_KEYWORDS = {
  "😀": "grinning face smiley happy smile",
  "😃": "grinning face with big eyes happy smile",
  "😄": "grinning face with smiling eyes happy smile",
  "😁": "beaming face with smiling eyes happy smile grin",
  "😆": "grinning squinting face happy smile",
  "😅": "grinning face with sweat sweat smile hot",
  "😂": "face with tears of joy laugh lol cry tear",
  "🤣": "rolling on the floor laughing rofl lol laugh",
  "😊": "smiling face with smiling eyes happy smile blush",
  "😇": "smiling face with halo angel innocent",
  "🙂": "slightly smiling face smile",
  "🙃": "upside-down face silly",
  "😉": "winking face wink",
  "😌": "relieved face calm peace",
  "😍": "smiling face with heart-eyes love heart like",
  "🥰": "smiling face with hearts love heart warm blush",
  "😘": "face blowing a kiss love kiss blow",
  "🔥": "fire hot lit burn",
  "❤️": "red heart love heart like",
  "👍": "thumbs up like agree ok yes",
  "👎": "thumbs down dislike no",
  "🥳": "partying face party celebrate birthday",
  "👋": "wave hello hand greeting",
  "👌": "ok hand yes good",
  "✌️": "peace victory hand sign",
  "👏": "clapping hands bravo praise",
  "🙏": "folded hands pray thank you please",
  "💪": "flexed biceps muscle strong power",
  "🧠": "brain mind intelligence",
  "👀": "eyes look see watch",
  "🐶": "dog puppy pet animal",
  "🐱": "cat kitten pet animal",
  "🦊": "fox animal wild",
  "🐻": "bear animal wild",
  "🐼": "panda animal wild cute",
  "🦁": "lion animal wild king",
  "🐸": "frog animal amphibian",
  "🐒": "monkey animal wild",
  "🐧": "penguin animal bird cold",
  "🐦": "bird flying animal",
  "🦄": "unicorn animal magic fantasy",
  "🐝": "bee honey insect bug",
  "🦋": "butterfly insect bug wings",
  "🕸": "spider web bug insect spooky",
  "🐍": "snake animal reptile",
  "🐬": "dolphin animal sea ocean",
  "🦈": "shark animal sea ocean predator",
  "👑": "crown king queen royal royalty",
  "🍏": "green apple fruit food fresh",
  "🍎": "red apple fruit food",
  "🍌": "banana fruit food yellow",
  "🍉": "watermelon fruit food summer",
  "🍓": "strawberry fruit food red",
  "🍒": "cherry fruit food red",
  "🍆": "eggplant vegetable food purple",
  "🥑": "avocado fruit food green",
  "🌶": "hot pepper spicy chili food red",
  "🧀": "cheese food yellow",
  "🍳": "cooking egg breakfast food",
  "🍔": "hamburger fast food beef burger",
  "🍟": "french fries potato fast food",
  "🍕": "pizza slice fast food cheese",
  "🥪": "sandwich bread lunch food",
  "🌮": "taco Mexican fast food",
  "🌯": "burrito Mexican fast food",
  "🍿": "popcorn movie theater snack food",
  "🍩": "donut dessert sweet breakfast",
  "🍪": "cookie dessert sweet snack",
  "🎂": "birthday cake celebrate dessert sweet",
  "🍰": "shortcake dessert sweet cake slice",
  "🍫": "chocolate bar sweet candy",
  "🍭": "lollipop sweet candy",
  "🥛": "glass of milk drink calcium",
  "☕️": "coffee cup hot tea drink mug",
  "🍵": "teacup drink hot green tea",
  "🍷": "wine glass drink alcohol party",
  "🍺": "beer mug drink alcohol pub bar",
  "🍻": "clinking beer mugs drink alcohol toast",
  "🥤": "cup with straw soda drink soft",
  "🎮": "video game controller gaming play",
  "🎳": "bowling ball pins sport game",
  "🎯": "bullseye target dart hit win",
  "🏈": "american football sport ball game",
  "🏀": "basketball sport ball game",
  "⚽️": "soccer football ball sport game",
  "🎾": "tennis ball racket sport game",
  "🎱": "pool 8 ball game billiards",
  "🏆": "trophy prize win gold reward",
  "🥇": "1st place medal gold prize win",
  "🎨": "artist palette paint draw art creative",
  "🎬": "clapper board movie cinema video director",
  "🎤": "microphone sing karaoke music audio",
  "🎧": "headphones music listen sound audio",
  "🎹": "musical keyboard piano music instrument",
  "🚗": "automobile car vehicle transport drive",
  "🚕": "taxi vehicle transport cab",
  "🚓": "police car vehicle siren",
  "🚑": "ambulance vehicle emergency medical",
  "🚒": "fire engine vehicle emergency",
  "🚜": "tractor vehicle farm agricultural",
  "🏍": "motorcycle vehicle transport motor",
  "🚲": "bicycle bike vehicle ride",
  "⛽️": "fuel pump gas station petrol car",
  "⚓️": "anchor ship sea navy boat",
  "⛵️": "sailboat boat sea ocean wind",
  "✈️": "airplane plane flight transport fly",
  "🚀": "rocket space fly mission",
  "🛸": "flying saucer ufo alien space",
  "⏰": "alarm clock time watch",
  "🏖": "beach umbrella sand ocean summer",
  "🏕": "camping tent outdoors nature forest",
  "🏢": "office building work business",
  "🏫": "school education study student",
  "🏰": "castle fortress royal building history",
  "📱": "mobile phone cell screen technology call",
  "💻": "laptop computer technology screen work",
  "📷": "camera photography photo picture capture",
  "📺": "television screen tv show display",
  "💡": "light bulb idea creative electricity",
  "💵": "dollar banknote cash money wealth",
  "💰": "bag of money cash wealth rich gold",
  "💳": "credit card bank transaction finance",
  "💎": "gem stone diamond jewelry expensive precious",
  "🔧": "wrench tool repair fix mechanical",
  "🔨": "hammer tool build construction",
  "🔫": "water pistol gun toy weapon",
  "💣": "bomb weapon explosive danger",
  "🚬": "cigarette smoking tobacco smoke",
  "⚰️": "coffin death funeral box spooky",
  "🔮": "crystal ball magic fortune teller future",
  "🧪": "test tube science chemistry experiment lab",
  "🧬": "dna helix science biology genetics",
  "💉": "syringe needle medical injection vaccine doctor",
  "💊": "pill medicine capsule drug health pharmacy",
  "💤": "zzz sleep tired snoring dream",
  "💬": "speech balloon chat text conversation comment",
  "💭": "thought balloon think dream mind",
  "💮": "white flower rosette stamp",
  "♨️": "hot springs steam bath relax",
  "💈": "barber pole hair cut salon",
  "🛑": "stop sign red warning traffic",
  "🔔": "bell ring notification alert sound",
  "🏁": "chequered flag finish race auto",
  "🚩": "triangular flag post marker sign",
  "🏳️‍🌈": "rainbow flag lgbt pride diversity",
  "🏴‍☠️": "pirate flag skull bones jolly roger",
};

export function getEmojiKeywords(emoji) {
  return EMOJI_KEYWORDS[emoji] || '';
}
